### ISSUE TITLE
Icons Won't Display if Name has Special Character

### ISSUE THREAD

**Issue by CatoThe1stElder** [CatoThe1stElder/WFRP-4th-Edition-FoundryVTT#106]
Notice that the icons with either a comma or parentheses in the name don't display.

![image](https://user-images.githubusercontent.com/43337293/62396401-f9c06b80-b527-11e9-9916-a92870d20eb4.png)

**Comment by moo-man** [comment]
Sounds like the common issue with unsafe characters in a URL. What do the paths to the images look like? I would remove all spaces and punctuation from them.
