### ISSUE TITLE
Readd Compendium footer to distinguish which compendia are owned

### ISSUE THREAD

**Issue by moo-man** [CatoThe1stElder/WFRP-4th-Edition-FoundryVTT#157]
![image](https://user-images.githubusercontent.com/28637157/63645476-b25f7200-c6c4-11e9-9932-27d84aa15742.png)
This should include `wfrp4e`, `world` or `<module-name>` depending on where the compendium came from. This data exists in the `compendium-footer` but is not displayed in 0.8.1 for some reason.
![image](https://user-images.githubusercontent.com/28637157/63645485-e175e380-c6c4-11e9-8816-c988e2cb1144.png)

**Comment by qennenat** [comment]
Completed
![image](https://user-images.githubusercontent.com/43337293/71067534-9414fa80-2129-11ea-86ec-7cc6736d3dbf.png)
