### ISSUE TITLE
Talent Test selection does not wrap properly

### ISSUE THREAD

**Issue by moo-man** [CatoThe1stElder/WFRP-4th-Edition-FoundryVTT#196]
![image](https://user-images.githubusercontent.com/28637157/65356330-cdd17600-dbb9-11e9-8039-2ecb7efd8132.png)

To replicate, add Perfect Pitch to an actor, open a Test dialog, and notice that the full talent test text is not shown.

**Comment by qennenat** [comment]
Fixed issue with references commit.
![image](https://user-images.githubusercontent.com/43337293/68583575-5ccc7300-0432-11ea-91f5-87ea9584c7a0.png)
