### ISSUE TITLE
Easy table access

### ISSUE THREAD

**Issue by SZzip** [CatoThe1stElder/WFRP-4th-Edition-FoundryVTT#221]
I created a small snippit to access the tables easier. Feel free to add it to the module.

$('.roll-type-select').find('.fa-dice-d20').attr("style", 'cursor: pointer;');
$('.roll-type-select').find('.fa-dice-d20').click(function(){
	let chatOptions = {user: game.user._id}
	if (['gmroll', 'blindroll'].includes(game.settings.get('core', 'rollMode')))
		chatOptions['whisper'] = ChatMessage.getWhisperIDs('GM');
	if (game.settings.get('core', 'rollMode') === 'blindroll')
		chatOptions['blind'] = true;
	var content = '<b><code>/table</code> Commands</b><br>'
	Object.entries(WFRP_Tables).forEach(function(value){ 
		content += '<a data-table=\'' + value[0] + '\' class=\'table-click\'><code>' + value[0] + '</code> - ' + value[1].name + '<br></a>'
	})
	chatOptions['content'] = content;
	ChatMessage.create(chatOptions,false)
})

**Comment by moo-man** [comment]
Am I correct in that this addresses issue #145 ? Is that the purpose here or is there something else added as well?

I ask this because #146 has already been fixed, you can click on tables in the menu to roll them
