### ISSUE TITLE
Refactor template.json for upcoming FVTT 0.4.0 change

### ISSUE THREAD

**Issue by moo-man** [CatoThe1stElder/WFRP-4th-Edition-FoundryVTT#233]

**Comment by qennenat** [comment]
If I may ask, why do we need to refactor the template.json for the upcoming FVTT 0.4.0 change?

**Comment by moo-man** [comment]
Refer to this gitlab issue https://gitlab.com/foundrynet/foundryvtt/issues/1614

You can see the completed refactor in the dev-backend branch under the `template-new.json` file
