### ISSUE TITLE
Trait Details have black text boxes

### ISSUE THREAD

**Issue by moo-man** [CatoThe1stElder/WFRP-4th-Edition-FoundryVTT#235]

**Comment by qennenat** [comment]
Specifically where do trait details have black text boxes? The actor sheet displays them correctly...
![image](https://user-images.githubusercontent.com/43337293/71067848-2c12e400-212a-11ea-91cc-27fe4f318c3e.png)

**Comment by qennenat** [comment]
> Specifically where do trait details have black text boxes? The actor sheet displays them correctly...
> ![image](https://user-images.githubusercontent.com/43337293/71067848-2c12e400-212a-11ea-91cc-27fe4f318c3e.png)

Nevermind, I found the issue and fixed it.
![image](https://user-images.githubusercontent.com/43337293/71068527-c293d500-212b-11ea-8ad8-cec66c2da183.png)
