### ISSUE TITLE
Complete and Add Item Icons

### ISSUE THREAD

**Issue by CatoThe1stElder** [CatoThe1stElder/WFRP-4th-Edition-FoundryVTT#32]

**Comment by moo-man** [comment]
- [ ] Weapons
- [ ] Armor
- [ ] Ammunition
- [ ] Spells
- [ ] Prayers
- [ ] Skills (simple)
- [ ] Talents
- [ ] Traits (simple)
- [ ] Injuries
- [ ] Psychologies (simple)
- [ ] Diseases (simple)
