### ISSUE TITLE
Allow more than three folder levels in Journals

### ISSUE THREAD

**Issue by manueleiria** [CatoThe1stElder/WFRP-4th-Edition-FoundryVTT#351]
While it's not possible to create more than three levels for Journal folders, it's possible to move a three-tier journal inside another folder, creating four tiers. However, doing so will place the 4th tier and its items visible in the root as well.
I organize folders by geography, and would like to have additional levels in which to nest my folders.
Example provided of current bug, but can be treated as an improvement:

![image](https://user-images.githubusercontent.com/829117/77249375-927f3500-6c38-11ea-820f-191c8bde428e.png)

**Comment by moo-man** [comment]
Hi, thanks for the issue report! I'm completely in agreement with you and I would also like to see more folder levels added, I do exactly what you do and want to subdivide journals into folders as much as I can. However, this does not really pertain to the WFRP system as it is a core Foundry design decision, so I'm closing it. 

As far as I know, more folder depth causes UI issues, and isn't planned. But I would search the Foundry gitlab issue board https://gitlab.com/foundrynet/foundryvtt/-/issues or ask Atropos personally in the Foundry discord as to his plans for this.
