### ISSUE TITLE
Localization fixes

### ISSUE THREAD

**Issue by moo-man** [CatoThe1stElder/WFRP-4th-Edition-FoundryVTT#352]
## Untranslatable Strings

- [x] Characteristic Abbreviations

- [x] Missing LoreDescription.Shadows in en.json

## Bugs

- [ ] /char - career button

- [x] Items - Size (All specifications as well), Hardy, Small, Mindless, Construct, Armour, Swarm

**Comment by sladecraven** [comment]
Translation of 'Weapon Properties'

**Comment by LeRatierBretonnien** [comment]
Allow translation of 'yards' in Range (for example)

**Comment by LeRatierBretonnien** [comment]
Description of 'Draught Horse' is wrong in trappings.db : this is not a war horse :)
Same for 'Monkey'
Same for 'Riding Horse'
Same for 'Poney'

Description of 'Saddlebags' is wrong

**Comment by LeRatierBretonnien** [comment]
Enable translation of money : Brass Penny/Gold Crown/Silver Shilling

**Comment by Moilunator** [comment]
Hi Moo Man, I'm French and I help translate the compendium psychologies and I don't find "Love" in it. Is it an oversight or a choice ?

**Comment by moo-man** [comment]
@Moilunator Love was an example custom psychology, I'm not sure if that's detailed in the French translation, I would imagine it is, I can send you the text if not.

**Comment by Moilunator** [comment]
I've Love in the french rulesbook, but Love is not included in the compendium (Camaraderie, Phobia and Trauma are).

**Comment by moo-man** [comment]
@Moilunator Sorry my apologies, I misinterpreted. Yeah, looks like an oversight, I'll add it next update

**Comment by LeRatierBretonnien** [comment]
![image](https://user-images.githubusercontent.com/1085008/78218476-231e0680-74be-11ea-9ae4-76ee8f613977.png)

CSS (table/celll?) overflow with "Augmentations", cf snapshot

**Comment by LeRatierBretonnien** [comment]
When clicking on a prayer  spell (blessing or another), the "Roll" window is displayed, but the skill linked with it is "Fellowship", instead of "Pray" -> this can lead to wrong rolls results.

**Comment by moo-man** [comment]
@sladecraven 
Is this a localization issue? If you've changed the skill names it would be expected

**Comment by LeRatierBretonnien** [comment]
@moo-man 
OK, yes, skill names are translated. So how to manage this properly ? On your side or on my side ?

**Comment by moo-man** [comment]
@sladecraven that'd be my side, I've gotta add support to recognize localized item names

**Comment by LeRatierBretonnien** [comment]
Ok, clear !

**Comment by LeRatierBretonnien** [comment]
Weapon qualities must be handled thru 'translation'. For example : 
`
dice-wfrp4e.js:  if (weapon.properties.qualities.includes("Impale")
`
should be (i guess) : 
`
dice-wfrp4e.js:  if (weapon.properties.qualities.includes("WFRP4E.Properties.Impale")
`

**Comment by sladecraven** [comment]
Management of translated talents that provide bonuses to characteristics (ie + 5 Willpower and so on).

**Comment by Antares117** [comment]
Bonjour je viens de voir que les dégats de la grande Ache ne sont pas bon : + au lieu de +6.
Et encore merci pour le travail que vous effectué

**Comment by LeRatierBretonnien** [comment]
When using names with a ' inside, the findItem function is failing, and the associated text is not displayed in the chat.
Example : In french, the translation of "Ear Bash" is "Frappe à l'oreille" -> this outputs an error in line 801 of dice-wfrp4e.js (dev-backend branch) when clicking in the critical name in the chat.
Without the ' (ie "Frappe à l oreille"), it does not raise the eror
**->FIXED on FR SIDE - Wrong char. used by translator**

**Comment by sladecraven** [comment]
Weapon group description are not 100% keyed : 
`
// Weapon Group Descriptions
WFRP4E.weaponGroupDescriptions = {
        "basic": "Basic",
        "cavalry": "WFRP4E.GroupDescription.Cavalry",
        "fencing": "Fencing",
        "brawling": "Brawling",
        "flail": "WFRP4E.GroupDescription.Flail",
        "parry": "WFRP4E.GroupDescription.Parry",
        "polearm": "Polearm",
        "twohanded": "Two-Handed",
        "blackpowder": "WFRP4E.GroupDescription.Blackpowder",
        "bow": "Bow",
        "crossbow": "WFRP4E.GroupDescription.Crossbow",
        "entangling": "Entangling",
        "engineering": "WFRP4E.GroupDescription.Engineering",
        "explosives": "WFRP4E.GroupDescription.Explosives",
        "sling": "Sling",
        "throwing": "WFRP4E.GroupDescription.Throwing",
};
`
For example, "bow" should be "WFRP4E.GroupDescription.Bow" and so on

**Comment by LeRatierBretonnien** [comment]
When searching a skill for a weapon, the search key is not enough robust.
In actor/actor-wfrp4e.js, the  line : 
`
weapon.skillToUse = skills.find(x => x.name.toLowerCase().includes(weapon.data.weaponGroup.value.toLowerCase()))
`
Should be : 
`
weapon.skillToUse = skills.find(x => `x.name.toLowerCase().includes("("+weapon.data.weaponGroup.value.toLowerCase()+")"))
`

This avoid selection of wrong skill when a part of the name is matching. This is the case for example for the word Arc (ie Bow in french) that match the skill Marchandage (ie Haggle in French).

**Comment by LeRatierBretonnien** [comment]
Allow translate of distance unit : yd/yds/yards should be keyed in lang/endjson (replaced by meters in other translations).

**Comment by LeRatierBretonnien** [comment]
/cond command should search in WFRP4E.conditions string, not keys, in order to allow searching in translated names.

**Comment by LeRatierBretonnien** [comment]
in actor-sheet.js, in line 361 : 
`
let improvId = weapons.find(w => w.name.toLowerCase() == "improvised weapon");
`
"improvised weapon" -> should be localized with NAME.Improvised

**Comment by LeRatierBretonnien** [comment]
In actor-sheet.js, line 382, 
`
let skill = this.actor.items.find(s => s.data.name == game.i18n.localize("NAME.Enurance") && s.type == "skill")
`
"NAME.Enurance" -> should be NAME.Endurance

**Comment by JiDW** [comment]
the utility function "allMoneyItems" is using English labels to look into the compendium for adding GC/SS/BP to new actors. 

utility-wfrp4e.js, line 679
