### ISSUE TITLE
CSS Refactor 

### ISSUE THREAD

**Issue by moo-man** [CatoThe1stElder/WFRP-4th-Edition-FoundryVTT#363]
The CSS on item headers needs to be responsive to changes in length - notice the translation has screwed up all the header positioning. 
![image](https://user-images.githubusercontent.com/28637157/79079750-88e86a80-7cd6-11ea-8714-8f3ccae4fa56.png)

**Comment by qennenat** [comment]
On it

**Comment by JiDW** [comment]
Hi @CatoThe1stElder , I was looking at this last night and it is related to an issue with a translation used in place of an id in the html template.
I'm sorry for not calling it sooner! I was waiting for my 0.5.4 files to test it before anything else.

I've created a pull request #364 for this, but there is a lot more work to do on the css to make it perfectly responsive. 
Right now, I've forced the width of the elements to the english translation on the Skill tabs.

(I've tried to contact you on Discord)
