### ISSUE TITLE
Removing talents (with bonus to attributes) doesn't remove the bonus

### ISSUE THREAD

**Issue by ZigmundKreud** [CatoThe1stElder/WFRP-4th-Edition-FoundryVTT#367]
Hello guys,

Just to point out that when you add, for instance, the Talent "savvy" to a character, it applies the +5 bonus to intelligence, but when you remove it, the bonus remains. 

As bonuses given by talents are not tracked as "specific" in the character sheet, this could quickly lead to wrong character sheets with 5 free augmentations each time.

Is this mechanic intended ?

Good job anyway. ;)

**Comment by moo-man** [comment]
The bonus should be removed so this is a bug, thanks.

**Comment by ZigmundKreud** [comment]
Seems to work with the last update...
Thank you !
