### ISSUE TITLE
Edit test doesn't work anymore

### ISSUE THREAD

**Issue by thiravet** [CatoThe1stElder/WFRP-4th-Edition-FoundryVTT#368]
Hi 
I just installed Foundry 5.5 and WFRP 1.2. I tried to edit a test but now it's impossible to validate the modification. After modification if i click in another place, it stays in edit mode. If I push again on "Edit test", it doesn't take into account my modification.
I play under Windows10.
Thanks for this marvellous work

**Comment by JiDW** [comment]
It seems there was a small change in the API that broke this feature in 0.5.5. PR #371 should fix it for next release
