### ISSUE TITLE
impale, penetrating, hack and undamaging are not detected when you apply the damage.

### ISSUE THREAD

**Issue by thiravet** [CatoThe1stElder/WFRP-4th-Edition-FoundryVTT#378]
some weapons qualities are not detected when you apply the damage.
I tested with pistol and 2-handed axe and unarmed. Impale, penetrating, hack and undamaging are not taken into account.
I think you have to correct in actor-wfrp4e.js, the following lines (2964-2971 in the version on my computer 1.2.3):
      _if (opposeData.attackerTestResult.weapon) // If the attacker is using a weapon
      {
        // Determine its qualities/flaws to be used for damage calculation
        weaponProperties = opposeData.attackerTestResult.weapon.properties;
        penetrating = weaponProperties.qualities.includes("PROPERTY.Penetrating")
        undamaging = weaponProperties.flaws.includes("PROPERTY.Undamaging")
        hack = weaponProperties.qualities.includes("PROPERTY.Hack")
        impale = weaponProperties.qualities.includes("PROPERTY.Impale")
      }_
by using  _game.i18n.localize()_
e.g.
_impale = weaponProperties.qualities.includes(game.i18n.localize("PROPERTY.Impale"))_

**Comment by moo-man** [comment]
Thanks, I can't believe I forgot to actually localize the keys
