### ISSUE TITLE
issue with editing channeling result

### ISSUE THREAD

**Issue by thiravet** [CatoThe1stElder/WFRP-4th-Edition-FoundryVTT#381]
When we edit channeling results (when we use Fortune point e.g.), the computed result is not good. The SL is strangely updated with the CN value if i understood.

I modified the code in dice-wfrp4e.js to avoid editing spell.data.cn.SL and keep in memory the previous data. It seems it works.

L555-585 in the current version

    else // Successs - add SL to spell for further use
    {
      testResults.description = game.i18n.localize("ROLL.ChannelSuccess")

      // Optional Rule: If SL in extended test is -/+0, counts as -/+1
      if (Number(SL) == 0 && game.settings.get("wfrp4e", "extendedTests"))
        SL = 1;

      // Critical Channel - miscast and set SL gained to CN
      if (testResults.roll % 11 == 0)
      {
        testResults.extra.color_green = true;
        SL = spell.data.cn.value;
        testResults.extra.criticalchannell = game.i18n.localize("ROLL.CritChannel")
        if (!testData.extra.AA)
          miscastCounter++;
      }
    }

    // Add SL to CN and update actor
    SL = spell.data.cn.SL + Number(SL);
    if (SL > spell.data.cn.value)
      SL = spell.data.cn.value;
    else if ( SL < 0)
      SL = 0;

    actor.updateEmbeddedEntity("OwnedItem",
    {
      _id: spell._id,
      'data.cn.SL': SL
    });

**Comment by moo-man** [comment]
Thanks for this fix! Do you want to submit a PR or just have me include this in the next release?

**Comment by thiravet** [comment]
you can include that in the next release
