### ISSUE TITLE
Resolve the issue with tables and Browse Files permissions

### ISSUE THREAD

**Issue by moo-man** [CatoThe1stElder/WFRP-4th-Edition-FoundryVTT#383]
Currently, players need the Browse Files permission to read the table files.

Option 1: Force permissions to allow all players to read files - GM may not want this
Option 2: Use sockets to request files or table rolls from the GM - complicated and messy
Option 3: Use Foundry Tables - ... I like my tables

**Comment by JiDW** [comment]
What does the "Browser Files" permission allows exactly? For what reasons a GM would want to turn it off?

**Comment by moo-man** [comment]
Browser permission allows players to open the file browser, which many would not want, obviously.

Blocking browser permission also blocks the use of `FilePicker.browse`, which is what clients use to read tables.

**Comment by JiDW** [comment]
Could we not just load every tables in memory from system.json?
Instead of having "career.json", add a career.js with a careerTable = {}; ?

**Comment by moo-man** [comment]
My tables are already a larger barrier for entry than normal Foundry tables, so I'd prefer people be able to just add another table file and have it work easily.

**Comment by JiDW** [comment]
Hmm I see, but add another file where?
Directly is the system directory? 

Loading the files in memory would just need to add an entry to a list of tables somewhere. It is too complicated? I mean, considering the alternative of course. Being able to somehow limit the browsing permission to a specific directory would be better of course.

**Comment by moo-man** [comment]
With the addition of hiding folders in the file picker I don't think this is worthy of a refactor anymore. What are your thoughts @JiDW ?
