### ISSUE TITLE
Add a system for spending "Fortune" points

### ISSUE THREAD

**Issue by JiDW** [CatoThe1stElder/WFRP-4th-Edition-FoundryVTT#384]
There is currently two things (out of 3) that could be handled by the system:

* Rerolling a test
* Adding +1 SL to a test

I suggest to add either:
- a contextual menu to a roll with the following items available for the players who rolled => 
Reroll (-1 Fortune)
Add +1 SL (-1 Fortune)

or

- a private card chat after a roll with the following elements =>
Two buttons for reroll + adding SL
The remaining fortune points

Either way, another chat card is send to everybody to let them know that a fortune point has been used and how.
For a reroll, we also send a new roll (same target/modifiers)
For a +1SL, I suggest we just edit the previous roll to limit spams in the chat.

I'm not sure about the contextual vs card.

I'm not a fan of contextual menu because it is hidden from the players and it requires more training time. The GM has to know about it and tell his players
But another chat card, even if private, could be a bit much considering we already have a lot of chat card sent during a fight.

I think I still prefer the chat card tho, any thoughts?

**Comment by moo-man** [comment]
I dislike the extra chat card, as you said, it would clutter up the chat menu and be, to me, incredibly annoying to see it for every single roll you do.

I am definitely in support of the contextual menu, I'm not sure about your reservations, the 'training' needed is very minimal. It may be hidden, but there can be ways to make it more apparent, such as an icon+tooltip to tell the user that they can right click this card.

**Comment by JiDW** [comment]
Oh yeah, an icon is a very good idea, best of both worlds!

Well, it could be only me but the first time I discovered your system, the only thing that lost me was the "Apply damage" contextual menu. I figured it out thanks to a tutorial video but everything else was so simple that I didn't think of that in the first place while discovering the system without reading anything about it
