### ISSUE TITLE
Create a /help command

### ISSUE THREAD

**Issue by herveDarritchon** [CatoThe1stElder/WFRP-4th-Edition-FoundryVTT#390]
I propose to implement a /help chat command to display all the chat command available with WFRP set of rules.

Then we will discuss later how to help people to find out the /help command.

**Comment by herveDarritchon** [comment]
In the file chatMessage.js, there is a lot of simple equals (ie. if (command[0] == "/table")). Is there a reason to do that instead of the triple equals that check the type (ie. if (command[0] === "/table")) ?

If there is a reason is it the way you have to code in Foundry VTT js framework ?

If not, I will change all the "==" by "===" in the file.

**Comment by herveDarritchon** [comment]
Hi,

At this point, the result of the commande /help does this :

<img width="347" alt="Capture d’écran 2020-04-26 à 14 00 36" src="https://user-images.githubusercontent.com/5511927/80306945-6ff7b300-87c6-11ea-8151-e738c41c5775.png">

I can add a few things :

- an example for each command
- a link to the wiki page (https://github.com/CatoThe1stElder/WFRP-4th-Edition-FoundryVTT/wiki/Chat-Commands)

I'd like to have your opinion.

what do you think ? It's ok like that, more stuff, less stuff ?

**Comment by moo-man** [comment]
Examples would be great, but it's looking good so far! Also yeah there's no reason behind me using == over ===
