### ISSUE TITLE
Removing paid talents from the Character sheet doesn't refill spent XP

### ISSUE THREAD

**Issue by ZigmundKreud** [CatoThe1stElder/WFRP-4th-Edition-FoundryVTT#398]
Hi, 

When a Talent is added to a character sheet, and the dialog button "pay with XP" is used, when the talent is removed, XP isn't restored like for skills.

If not a bug, this could be a nice feature (if possible to implement).

Cheers,
Zigmund

**Comment by moo-man** [comment]
This is already implemented, right click on the advancement indicator

**Comment by ZigmundKreud** [comment]
Oh great ! I didn't see that...
Thanks
