### ISSUE TITLE
issue with damage when there is a size difference (more than 1)

### ISSUE THREAD

**Issue by thiravet** [CatoThe1stElder/WFRP-4th-Edition-FoundryVTT#402]
I think you have to replace in opposed-wfrp4.js the line 166

_if (sizeDiff >= 2)_

by 

_else if (sizeDiff >= 2)_

If you don't do that such b!g guys gain Damaging AND Impact. And this should not be the case.

Another solution is to replace line 155 by

_if (sizeDiff == 1)_

**Comment by moo-man** [comment]
x2 should indeed get both damaging and impact and x2 damage, it's a bit overkill I agree but that's the way they made it.

**Comment by thiravet** [comment]
I can make an error but I don't agree with you.
The rules are:
"Its weapons gain the Damaging Quality if the creature is
one step larger, and Impact if two steps or more larger."
Then we have:
one step larger=> Damaging
two steps or more => Impact.

(for damaging they don't tell "one step larger or more")

**Comment by moo-man** [comment]
While I agree with you and the interpretation, I distinctly remember a dev clarification on this. Let me ask around and see if I can find it.

**Comment by moo-man** [comment]
![image](https://user-images.githubusercontent.com/28637157/80675667-a9584900-8a7a-11ea-9bae-3d3c09f0df61.png)
Ubersreik Adventures - Page 30

**Comment by thiravet** [comment]
ok thank you for this research. I find that this is an error of game design. But this is an official source then it's normal to apply that in fvtt.

**Comment by moo-man** [comment]
Yeah, I agree, one of the many changes I've made for my own game!
