### ISSUE TITLE
Add the possibility to force the "+" XP on any skill

### ISSUE THREAD

**Issue by JiDW** [CatoThe1stElder/WFRP-4th-Edition-FoundryVTT#421]
Simple feature to adapt to some homebrews to allow simplified XP spending on a out-of-career skill

I propose to add a checkbox in the skill detail window: "Allow XP advancement mark" that will overrule to career system for this "+" mark.

I'm up to add this if Moo agrees to the idea.

(note to myself: ping gman95 on Discord once its done)

**Comment by moo-man** [comment]
Agreed, also useful for the talents that add skills
