### ISSUE TITLE
Hedge Apprentice / Channeling Skill

### ISSUE THREAD

**Issue by alvileiz** [CatoThe1stElder/WFRP-4th-Edition-FoundryVTT#422]
When click to add career skill "channeling" in Hedge Apprentice Tab Skills Nothing happens
![Channeling](https://user-images.githubusercontent.com/54315327/82700753-bbd33600-9c66-11ea-9106-7c8f41ada0d7.png)
.

**Comment by moo-man** [comment]
Change the spelling in the career to "Channelling" 

Sorry, it's a common issue that I've fixed before but it keeps cropping up for some reason. I'll take a look again.

**Comment by alvileiz** [comment]
> Change the spelling in the career to "Channelling"
> 
> Sorry, it's a common issue that I've fixed before but it keeps cropping up for some reason. I'll take a look again.

No problem! Keep on with the good work! You are awesome!
