### ISSUE TITLE
Special Dice roll in the interface UI not working anymore

### ISSUE THREAD

**Issue by guillaumecd15** [CatoThe1stElder/WFRP-4th-Edition-FoundryVTT#425]
Hi, in the UI interface to roll the test, we could not anymore do a blind , private or public roll
no options are listed, it's a public one by default.

**Comment by guillaumecd15** [comment]
![bug](https://user-images.githubusercontent.com/65849544/82754174-77ad7600-9dcb-11ea-94ea-c7937c949693.png)

**Comment by guillaumecd15** [comment]
Why this topic is closed? i ve no feedback on the issue

**Comment by moo-man** [comment]
Because you closed it 👀 
![image](https://user-images.githubusercontent.com/28637157/82923344-676ad780-9f40-11ea-94c6-a0914a0a72a5.png)

Sorry for no feedback, there's a fix coming in 1.5.0

**Comment by guillaumecd15** [comment]
Thanks for your feedbackWhen will you release the version 1.5 ?    De : RussellEnvoyé le :mardi 26 mai 2020 18:03À : CatoThe1stElder/WFRP-4th-Edition-FoundryVTTCc : guillaumecd15; State changeObjet :Re: [CatoThe1stElder/WFRP-4th-Edition-FoundryVTT] Special Dice roll in the interface UI not working anymore (#425) Because you closed it 👀Sorry for no feedback, there's a fix coming in 1.5.0—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by guillaumecd15** [comment]
> Because you closed it 👀
> ![image](https://user-images.githubusercontent.com/28637157/82923344-676ad780-9f40-11ea-94c6-a0914a0a72a5.png)
> 
> Sorry for no feedback, there's a fix coming in 1.5.0

Thx , when will you release the version 1.5.0 ?

**Comment by moo-man** [comment]
Hopefully soon, it's a big update and needs some testing. It's available in the `staging` branch right now if you're inclined, just be aware it could have some bugs. My goal is to release within a week or so.

**Comment by guillaumecd15** [comment]
I assume the manifest is the following :
https://raw.githubusercontent.com/CatoThe1stElder/WFRP-4th-Edition-FoundryVTT/staging/system.json

**Comment by moo-man** [comment]
No you'll have to download the zip manually from here https://github.com/CatoThe1stElder/WFRP-4th-Edition-FoundryVTT/archive/staging.zip

Rename it `wfrp4e` and stick it in your systems folder.

Be sure to post any problems you find in here! https://github.com/CatoThe1stElder/WFRP-4th-Edition-FoundryVTT/issues/426

**Comment by guillaumecd15** [comment]
Thanks , going to test it ,

**Comment by guillaumecd15** [comment]
![image](https://user-images.githubusercontent.com/65849544/82925095-8fc4f700-9f7d-11ea-8fff-e7758cb5dce7.png)
First look, a layout issue, not blocking at this stage
issue with special dice is solved.

**Comment by moo-man** [comment]
I don't get this issue, does it happen only when translated?

**Comment by guillaumecd15** [comment]
get the same in english
![image](https://user-images.githubusercontent.com/65849544/82925522-137ee380-9f7e-11ea-8c2d-242d35eaa9c9.png)

**Comment by moo-man** [comment]
Are you on discord? maybe we can discuss better there

**Comment by guillaumecd15** [comment]
i could not chat right now, sorry

**Comment by guillaumecd15** [comment]
i get his issue only with Player sheet, not for NPC or monsters

**Comment by moo-man** [comment]
I've left a comment in the #426 lets move the discussion there
