### ISSUE TITLE
Fixes for 1.5.0

### ISSUE THREAD

**Issue by moo-man** [CatoThe1stElder/WFRP-4th-Edition-FoundryVTT#426]
Compile graphical issues that should be resolved before releasing 1.5.0

- [x] **Ingredient header alignment**

- [x] **Weird Spacing in ambitions**

**Comment by moo-man** [comment]
Issue from user @guillaumecd15
![image](https://user-images.githubusercontent.com/28637157/82926001-24aafe80-9f44-11ea-9206-c54fc88a59c8.png)

Could you provide what browser (or if you're using electron), resolution, maybe any other details to reproduce? The sheets are resizable now, what is your sheet at to reproduce this? minimum?

**Comment by guillaumecd15** [comment]
Edge Chrome,

**Comment by guillaumecd15** [comment]
I tried to resize too, issue still here

**Comment by guillaumecd15** [comment]
same issue with firefox

**Comment by moo-man** [comment]
Well when you can, could you message me a game link so I can try it out personally?

**Comment by guillaumecd15** [comment]
use this link
http://92.157.71.1:30000
player : debug
pass : war2020

**Comment by moo-man** [comment]
I've saved the info but deleted the comment because it shows your IP.

Regardless, I can't login, are your ports forwarded?

**Comment by guillaumecd15** [comment]
i ve reset the password with the same war2020

**Comment by guillaumecd15** [comment]
port are forwarded correctly ( we use to play )

**Comment by guillaumecd15** [comment]
should be better , i was on wifi , sorry
