### ISSUE TITLE
Error. No damage values (after loading scene with ongoing combat)

### ISSUE THREAD

**Issue by mateusz-winiarski** [CatoThe1stElder/WFRP-4th-Edition-FoundryVTT#441]
I started combat encounter in a scene. Logged out and closed FoundryVTT.
Later after opening scene again there was an damage values error.
![image](https://user-images.githubusercontent.com/14980578/83657643-66314e80-a5c1-11ea-9df8-05cab3b0275c.png)

Hope that helps.

**Comment by moo-man** [comment]
There's no damage value because the defender won.
