### ISSUE TITLE
Some of the Trapping Icons don't load correctly

### ISSUE THREAD

**Issue by hamofficer** [CatoThe1stElder/WFRP-4th-Edition-FoundryVTT#447]
I believe its because Linux is case sensitive atleast that was pointed out as I accidently reported that issue to another warhammer wfrp 4th module.
aka they are taken and not missing but the Capitalization breaks them so they don't show up.

[Capitalization mistakes]
- The Rapiers 
- The Foil 
- The Daggers
- The Pike 
- The Halberd
- The Blunderbuss
- The Heavy Crossbow
- The Pick
- The shortbow
- The Whip

[Icons not selected or just blank selected instead of the icon in the systems wfrp folder]
Parchment/sheet
has an icon in the folder but isn't selected
systems/wfrp4e/icons/equipment/book_documents/basic-parchmentsheet.png

The Pole (3 yards)
has an icon in the folder but isn't selected
systems/wfrp4e/icons/equipment/tools_and_kits/3-yds.png

Flask of Spirits (this could be done on purpose from your side if it is then ignore
has no icon selected but should be either the Flask Icon 
equipment/packs_and_containers/flask.png
or one of the spirits-pint.png under equipment/food_drink_and_lodging

[Icons not there more of like a reminder that icons could be needed]
- Amputated Part Teeth
- Amputated Part Toes
- Amputated Part Tonguege

**Comment by ivan-hr** [comment]
Same problem here. Running foundryvtt also on linux.

**Comment by moo-man** [comment]
Thanks, has been addressed, except for injuries, not sure what to put for those lol
