### ISSUE TITLE
Bug after using Fortune Point

### ISSUE THREAD

**Issue by rajmund10** [CatoThe1stElder/WFRP-4th-Edition-FoundryVTT#448]
Dumb bug, but it happend on my game by accident. After using Fortune Point to add +1SL and still NOT PASSING it, and then rerolling test with another test fortune point, rerolled test will be always failed. I think on the other test, game take -SL from previous roll.

**Comment by JiDW** [comment]
Hello! Thanks, this will be fixed in the upcoming hotfix
