### ISSUE TITLE
Wrong type of item : Hammer 

### ISSUE THREAD

**Issue by LeRatierBretonnien** [CatoThe1stElder/WFRP-4th-Edition-FoundryVTT#460]
The Hammer should be in 'Weapons' instead of 'Tools & Kit"

**Comment by moo-man** [comment]
No, there is no "hammer" weapon, there is a hammer tool.

**Comment by LeRatierBretonnien** [comment]
OK, i was thinking of a mistake, because there is also a 'Gavel', which translate to the same word in french
