### ISSUE TITLE
Fencer (1st level of Duellist) has wrong status.

### ISSUE THREAD

**Issue by mateusz-winiarski** [CatoThe1stElder/WFRP-4th-Edition-FoundryVTT#462]
Rulebook 4ed says (p. 71) fencer has status Silver 3 not Silver 1.

**Comment by moo-man** [comment]
I don't see this 
![image](https://user-images.githubusercontent.com/28637157/85327806-332dfc80-b495-11ea-95a0-a788949abe93.png)

First career level, Standing is 3

**Comment by mateusz-winiarski** [comment]
Yes, it's ok now. I've updated module. Sorry for trouble. I will check module version next time.
