### ISSUE TITLE
Missing translation key with 'Pay' button for items

### ISSUE THREAD

**Issue by LeRatierBretonnien** [CatoThe1stElder/WFRP-4th-Edition-FoundryVTT#463]
In file `templates/chat/post-item.html` : 

The line : 
`<a class='chat-card-button market-button' data-button='payItem' data-pay="{{data.price.gc}}gc{{data.price.ss}}ss{{data.price.bp}}bp">{{localize "MARKET.PayForItem"}}</a>`
should be : 
`<a class='chat-card-button market-button' data-button='payItem' data-pay="{{data.price.gc}}{{localize "MARKET.Abbrev.GC"}}{{data.price.ss}}{{localize "MARKET.Abbrev.SS"}}{{data.price.bp}}{{localize "MARKET.Abbrev.BP"}}">{{localize "MARKET.PayForItem"}}</a>`

**Comment by moo-man** [comment]
Have you tested this to make sure it still works?

**Comment by LeRatierBretonnien** [comment]
Yes, this is when testing that i discovered this issue.
