### ISSUE TITLE
Bug: experience, wounds and stats cannot be edited

### ISSUE THREAD

**Issue by PiotrZakrzewski** [CatoThe1stElder/WFRP-4th-Edition-FoundryVTT#474]
Sometimes, it might be related to importing (?) characters wounds and or experience cannot be modified anymore. Characteristics can be unblocked when you trigger update to one of them by adding or removing a talent that modifies them. I can provide a character export json if you think it helps you.

**Comment by moo-man** [comment]
Are you purposefully creating this issue on this repo?

This repo is not maintained anymore. For the current system, see https://github.com/moo-man/WFRP4e-FoundryVTT

**Comment by PiotrZakrzewski** [comment]
I didn't realise! I will recreate it there. Thanks!
