### ISSUE TITLE
Consider changing Combat Tab to prevent scrollbars within scrollbars

### ISSUE THREAD

**Issue by moo-man** [CatoThe1stElder/WFRP-4th-Edition-FoundryVTT#59]
Consider changing the list from being fixed height to being dynamic length - each list is as long as it needs to be to show all items (Like Spells, Prayers, Inventory lists). This would remove the need for scrollbars within each list.

The main issue with this would probably be the Armor boxes, since they are columned.

**Comment by CatoThe1stElder** [comment]
Your welcome.
