### ISSUE TITLE
Provide reminder of exchange rate 1 GC = 20 SS = 240 BP within Money menu bar

### ISSUE THREAD

**Issue by Phboujon** [CatoThe1stElder/WFRP-4th-Edition-FoundryVTT#71]
As in rulebook, showcase which is the characteristics are for the career path, and which open at each level

**Comment by Phboujon** [comment]
![Money](https://user-images.githubusercontent.com/7441270/61536632-58b8b780-aa35-11e9-843a-310a7db65fcf.png)

**Comment by moo-man** [comment]
Might could use some styling but this is how it'll be for now 
![image](https://user-images.githubusercontent.com/28637157/61574186-672cc080-aa81-11e9-8b7b-9111775a3bf6.png)
